# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tech-blog
spec:
  owner: core
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: all-boundaries-web
  description: Tech blob on testing and software design
  annotations:
    backstage.io/source-location: url:https://github.com/all-boundaries/website
    github.com/project-slug: all-boundaries/website
  tags:
    - hugo
  links:
    - url: https://allboundaries.net/
      title: All Boundaries
      icon: dashboard
spec:
  owner: core
  type: website
  lifecycle: production
  system: tech-blog

